version: "3.8"

services:
  frontend:
    build:
      context: ./food-delivery-frontend # ✅ Ensure this is correct
    ports:
      - "4200:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./food-delivery
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/fooddelivery
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fooddelivery
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
